Lab5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Lab5.Models;
using Lab5.ViewsModels;

namespace Lab5.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRepositoryProduct repositoryProduct;
        private readonly IRepositorySupplier repositorySupplier;

        public HomeController(IRepositoryProduct repo, IRepositorySupplier repos) { 
            repositoryProduct = repo;
            repositorySupplier = repos;
        }

        public IActionResult Index() => View(repositoryProduct.GetAllProducts);

        [HttpGet]
        public IActionResult Create()
        {
            SupplierViewModelDropDownList model = new SupplierViewModelDropDownList();
            model.Supplier = DropDownListpopulated();
            return View(model);
        }

        private List<SelectListItem> DropDownListpopulated()
        {
            return repositorySupplier.GetSupplier.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name

            }).ToList();
        }

        [HttpPost]
        public IActionResult Create(SupplierViewModelDropDownList mo)
        {
            if(!ModelState.IsValid)
            {
                mo.Supplier = DropDownListpopulated();
                return View(mo);
            }
            Product product = new Product();
            product.Name = mo.Product.Name;
            product.Category = mo.Product.Category;
            product.Price = mo.Product.Price;
            product.SupplierId = mo.Product.SupplierId;

            repositoryProduct.Create(product);
            return RedirectToAction("index");
           
            
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Product GetProduct = repositoryProduct.GetProduct(id);

            SupplierViewModelDropDownList model = new SupplierViewModelDropDownList
            {
                Product = GetProduct,
                Supplier = DropDownListpopulated()

            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(SupplierViewModelDropDownList mo)
        {
            if( !ModelState.IsValid)
            {
                mo.Supplier = DropDownListpopulated();
                return View(mo);
            }
            Product product = repositoryProduct.GetProduct(mo.Product.Id);
            product.Name = mo.Product.Name;
            product.Category = mo.Product.Category;
            product.Price = mo.Product.Price;
            product.SupplierId = mo.Product.SupplierId;

            repositoryProduct.Update(product);
            return RedirectToAction("index");

        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            repositoryProduct.Delete(id);
            return RedirectToAction("index");
        }

    }
}

Lab5/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab5.Models;
using Lab5.ViewsModels;

namespace Lab5.Controllers
{
    public class SupplierController : Controller
    {
        private readonly IRepositorySupplier repositorySupplier;
        private readonly IRepositoryProduct repositoryProduct;
        public SupplierController(IRepositorySupplier supplier, IRepositoryProduct repos)
        {
            repositorySupplier = supplier;
            repositoryProduct = repos;
        }

        public IActionResult Index()
        {
        
            return View(repositorySupplier.GetSupplier);
        }


        public IActionResult ViewProducts(int id)
        {
            ViewBag.SuuplierName = repositoryProduct.GetNameByIdSupplier(id);

            return View(repositoryProduct.GetProductByIdSupplier(id));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Supplier supplier)
        {
            if(!ModelState.IsValid)
            {

                return View(supplier);
            }

            repositorySupplier.Create(supplier);
           return RedirectToAction("index");
        }
        public IActionResult Edit(int id)
        {
            return View(repositorySupplier.GetSupplierById(id));
        }
        [HttpPost]
        public IActionResult Edit(Supplier supplier)
        {
            if (!ModelState.IsValid)
            {

                return View(supplier);
            }
            repositorySupplier.Update(supplier);
            return RedirectToAction("index");

        }

        public IActionResult Delete(int id)
        {
            repositorySupplier.Delete(id);
            return RedirectToAction("index");
        }

    }
}

Lab5/Views/Home/Create.cshtml
@model SupplierViewModelDropDownList
@{
    ViewData["Title"] = "Create";
}

@if (Model.Supplier.Count() ==0)
{
    <div class="text-center mt-1" >
        <h1 class=" text-danger"> Create New Supplier First Before Product </h1>
        <a class="btn btn-primary mb-4" asp-controller="Supplier" asp-action="Create"> Create New Supplier</a>
    </div>
}
else
{
    <div class="container m-5">
        <h1 class="h2Style"> Create Product</h1>
        <form asp-action="Create" method="post">

            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product.Name"></label>
                <input asp-for="Product.Name" class="form-control" />
                <span asp-validation-for="Product.Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Product.Category"></label>
                <input asp-for="Product.Category" class="form-control" />
                <span asp-validation-for="Product.Category" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Product.Price"></label>
                <input asp-for="Product.Price" class="form-control" />
                <span asp-validation-for="Product.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Supplier"></label>
                <select class="custom-select" asp-for="Product.SupplierId" asp-items="@Model.Supplier">
                    <option value="">Select</option>
                </select>
                <span asp-validation-for="Product.SupplierId" class="text-danger"></span>
            </div>
            <div>
                <button class="btn btn-primary"> Save </button>
                <a asp-action="index" class="btn btn-secondary"> Cancel </a>

            </div>
        </form>
    </div>
}

Lab5/Views/Home/Edit.cshtml
@model SupplierViewModelDropDownList
@{
    ViewData["Title"] = "Edit Product";
}


    <div class="container m-5">
        <h2 class="h2Style">Edit products </h2>
        <div>
            <form asp-action="Edit" method="post">

                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Product.Name"></label>
                    <input asp-for="Product.Name" class="form-control" />
                    <span asp-validation-for="Product.Name" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Product.Category"></label>
                    <input asp-for="Product.Category" class="form-control" />
                    <span asp-validation-for="Product.Category" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Product.Price"></label>
                    <input asp-for="Product.Price" class="form-control" />
                    <span asp-validation-for="Product.Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Supplier"></label>
                    <select class="custom-select" asp-for="Product.SupplierId" asp-items="@Model.Supplier">
                        <option value="">Select</option>
                    </select>
                    <span asp-validation-for="Product.SupplierId" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Product.Id" value="@Model.Product.Id" />
                <div>
                    <button class="btn btn-primary"> Edit </button>
                    <a asp-action="index" class="btn btn-secondary"> Cancel </a>

                </div>
            </form>

        </div>
    </div>

Lab5/Views/Home/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "List Products";
}

@if (Model.Count() == 0)
{
    <div class="text-center">
        <h2 > Empty products  </h2>
        <a class="btn btn-primary mb-4" asp-action="Create"> Create new Product</a>
    </div>
}
else
{

    <div class="container  mt-4 mb-5">
        <h2 class="h2Style">All products </h2>
        <a class="btn btn-primary mb-4" asp-action="Create"> Create new Product</a>
        <div>
            <table class="table table-sm table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Price</th>
                        <th>Supplier Name</th>
                        <td></td>
                    </tr>
                </thead>

                <tbody>
                    @foreach (Product p in Model)
                    {
                        <tr class="border-bottom ">
                            <td>@p.Id</td>
                            <td>@p.Name</td>
                            <td>@p.Category</td>
                            <td>@p.Price</td>
                            <td>@p.Supplier.Name</td>
                            <td>
                                <form method="post" asp-action="Delete">
                                    <a asp-action="Edit" asp-route-id="@p.Id" style="min-width:71.63px" class="btn btn-primary">Edit</a>
                                    <button class="btn btn-danger"> Delete </button>
                                    <input type="hidden" name="id" value="@p.Id" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>


    </div>
}